definitions:
  DTOs.CreateTaskRequest:
    properties:
      deadline:
        type: string
      description:
        type: string
      name:
        type: string
      priority:
        $ref: '#/definitions/enums.Priority'
    required:
    - name
    type: object
  enums.Priority:
    enum:
    - Low
    - Medium
    - High
    - Critical
    type: string
    x-enum-varnames:
    - Low
    - Medium
    - High
    - Critical
  enums.Status:
    enum:
    - Active
    - Completed
    - Overdue
    - Late
    type: string
    x-enum-varnames:
    - Active
    - Completed
    - Overdue
    - Late
  errors.ApplicationError:
    properties:
      code:
        type: string
      errors:
        additionalProperties:
          type: string
        type: object
      statusCode:
        type: integer
    type: object
  models.Task:
    properties:
      changedAt:
        type: string
      createdAt:
        type: string
      deadline:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      priority:
        $ref: '#/definitions/enums.Priority'
      status:
        $ref: '#/definitions/enums.Status'
    type: object
info:
  contact: {}
paths:
  /tasks:
    get:
      consumes:
      - application/json
      description: Get all tasks with optional sorting
      parameters:
      - description: Sorting
        enum:
        - CreateAsc
        - CreateDesc
        - PriorityAsc
        - PriorityDesc
        - DeadlineAsc
        - DeadlineDesc
        in: query
        name: sorting
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
        "500":
          description: Internal server error
      summary: Get all tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Create a new task
      parameters:
      - description: Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/DTOs.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/errors.ApplicationError'
        "500":
          description: Internal server error
      summary: Create a task
      tags:
      - tasks
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Delete task by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/errors.ApplicationError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/errors.ApplicationError'
        "500":
          description: Internal server error
      summary: Delete task
      tags:
      - tasks
swagger: "2.0"
